name: smart_prescription_scanner
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.11.1
  image_picker: ^0.8.6
  path_provider: ^2.1.5
  google_ml_kit: ^0.13.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  share_plus: ^10.1.4
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_gemini: ^3.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
